requires 'DBIx::Class';
requires 'DBIx::Class::EncodedColumn';
requires 'DBIx::Class::Schema::Loader';
requires 'DBIx::Class::TimeStamp';
requires 'Data::Pageset';
requires 'DateTime';
requires 'DateTime::Format::MySQL';
requires 'Gravatar::URL';
requires 'MojoX::Validator::Constraint::Email';
requires 'Mojolicious','4.63';
requires 'Mojolicious::Plugin::FillInFormLite';
requires 'Mojolicious::Plugin::HamlRenderer';
requires 'Mojolicious::Plugin::Validator';
requires 'Path::Tiny';
requires 'SMS::Send::KR::CoolSMS';
requires 'Text::Haml', '0.990114';
requires 'Try::Tiny';
