requires 'AnyEvent';
requires 'AnyEvent::HTTPD';
requires 'AnyEvent::Timer::Cron';
requires 'Data::Pageset';
requires 'DateTime';
requires 'DateTime::Format::Human::Duration';
requires 'FindBin';
requires 'Getopt::Long::Descriptive';
requires 'Gravatar::URL';
requires 'HTTP::Tiny';
requires 'JSON';
requires 'List::MoreUtils';
requires 'List::Util';
requires 'Mojolicious','5.48';
requires 'Mojolicious::Plugin::Authentication';
requires 'Mojolicious::Plugin::FillInFormLite';
requires 'Mojolicious::Plugin::HamlRenderer';
requires 'Mojolicious::Plugin::Validator';
requires 'Moo';
requires 'MooX::Types::MooseLike';
requires 'Object::Event';
requires 'OpenCloset::Schema', '0.001';
requires 'Path::Tiny';
requires 'SMS::Send::KR::CoolSMS', '1.002';
requires 'Scalar::Util';
requires 'Text::CSV';
requires 'Text::Haml', '0.990114';
requires 'Try::Tiny';
requires 'Unicode::GCString';
requires 'experimental';
requires 'namespace::clean';

# from git repository
requires 'git://github.com/aanoaa/p5-postcodify.git@v0.2.6';
