#!/bin/sh
export MOJO_HOME=.
export MOJO_CONFIG=app.conf
export OPENCLOSET_COOLSMS_API_KEY='abcde'
export OPENCLOSET_COOLSMS_API_SECRET='abcde'
export OPENCLOSET_APISTORE_ID='abcde'
export OPENCLOSET_APISTORE_API_STORE_KEY='abcde'
export OPENCLOSET_BODYKIT_ACCESSKEY='AK9b117ef1b1d64dcb68c9657ed26acf44'
export OPENCLOSET_BODYKIT_SECRET='783c13b27e86b73ba92c714457c0500b'
morbo -w app.conf -w templates -l 'http://*:5001' ./app.psgi
