package Opencloset::Constant;

our $STATUS_AVAILABLE      = 1;
our $STATUS_RENT           = 2;
our $STATUS_WASHING        = 3;
our $STATUS_REPAIRING      = 4;
our $STATUS_UNAVAILABLE    = 5;
our $STATUS_LATENESS       = 6;
our $STATUS_MISSING        = 7;
our $STATUS_RETURN         = 8;
our $STATUS_PARTIAL_RETURN = 9;

our $CATEOGORY_JACKET       = 0x0001;
our $CATEOGORY_PANTS        = 0x0002;
our $CATEOGORY_SHIRT        = 0x0004;
our $CATEOGORY_SHOES        = 0x0008;
our $CATEOGORY_HAT          = 0x0010;
our $CATEOGORY_TIE          = 0x0020;
our $CATEOGORY_WAISTCOAT    = 0x0040;
our $CATEOGORY_COAT         = 0x0080;
our $CATEOGORY_ONEPIECE     = 0x0100;
our $CATEOGORY_SKIRT        = 0x0200;
our $CATEOGORY_BLOUSE       = 0x0400;
our $CATEOGORY_JACKET_PANTS = $CATEOGORY_JACKET | $CATEOGORY_PANTS;
our $CATEOGORY_JACKET_SKIRT = $CATEOGORY_JACKET | $CATEOGORY_SKIRT;

our $CLOTH_DESIGNATED_FOR_MAN    = 1;
our $CLOTH_DESIGNATED_FOR_WOMAN  = 2;
our $CLOTH_DESIGNATED_FOR_UNISEX = 3;

1;
