package Opencloset::Constant;

our $STATUS_AVAILABLE      = 1;
our $STATUS_RENT           = 2;
our $STATUS_WASHING        = 3;
our $STATUS_REPAIRING      = 4;
our $STATUS_UNAVAILABLE    = 5;
our $STATUS_LATENESS       = 6;
our $STATUS_MISSING        = 7;
our $STATUS_RETURN         = 8;
our $STATUS_PARTIAL_RETURN = 9;

our $CATEOGORY_JACKET_PANTS  = -1;
our $CATEOGORY_JACKET_SKIRTS = -2;

our $CATEOGORY_JACKET    = 1;
our $CATEOGORY_PANTS     = 2;
our $CATEOGORY_SHIRT     = 3;
our $CATEOGORY_SHOES     = 4;
our $CATEOGORY_HAT       = 5;
our $CATEOGORY_TIE       = 6;
our $CATEOGORY_WAISTCOAT = 7;
our $CATEOGORY_COAT      = 8;
our $CATEOGORY_ONEPIECE  = 9;
our $CATEOGORY_SKIRT     = 10;
our $CATEOGORY_BLOUSE    = 11;

our $CLOTH_DESIGNATED_FOR_MAN    = 1;
our $CLOTH_DESIGNATED_FOR_WOMAN  = 2;
our $CLOTH_DESIGNATED_FOR_UNISEX = 3;

1;
